//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFMiddleware.JEEWebservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://messagereceiver.bank.com/", ConfigurationName="JEEWebservice.FileReceiverEndp")]
    public interface FileReceiverEndp {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément key de l'espace de noms  n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://messagereceiver.bank.com/FileReceiverEndp/messageReaderRequest", ReplyAction="http://messagereceiver.bank.com/FileReceiverEndp/messageReaderResponse")]
        WCFMiddleware.JEEWebservice.messageReaderResponse messageReader(WCFMiddleware.JEEWebservice.messageReaderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://messagereceiver.bank.com/FileReceiverEndp/messageReaderRequest", ReplyAction="http://messagereceiver.bank.com/FileReceiverEndp/messageReaderResponse")]
        System.Threading.Tasks.Task<WCFMiddleware.JEEWebservice.messageReaderResponse> messageReaderAsync(WCFMiddleware.JEEWebservice.messageReaderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class messageReaderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="messageReader", Namespace="http://messagereceiver.bank.com/", Order=0)]
        public WCFMiddleware.JEEWebservice.messageReaderRequestBody Body;
        
        public messageReaderRequest() {
        }
        
        public messageReaderRequest(WCFMiddleware.JEEWebservice.messageReaderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class messageReaderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileName;
        
        public messageReaderRequestBody() {
        }
        
        public messageReaderRequestBody(byte[] message, string key, string fileName) {
            this.message = message;
            this.key = key;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class messageReaderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="messageReaderResponse", Namespace="http://messagereceiver.bank.com/", Order=0)]
        public WCFMiddleware.JEEWebservice.messageReaderResponseBody Body;
        
        public messageReaderResponse() {
        }
        
        public messageReaderResponse(WCFMiddleware.JEEWebservice.messageReaderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class messageReaderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string messageReceived;
        
        public messageReaderResponseBody() {
        }
        
        public messageReaderResponseBody(string messageReceived) {
            this.messageReceived = messageReceived;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileReceiverEndpChannel : WCFMiddleware.JEEWebservice.FileReceiverEndp, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileReceiverEndpClient : System.ServiceModel.ClientBase<WCFMiddleware.JEEWebservice.FileReceiverEndp>, WCFMiddleware.JEEWebservice.FileReceiverEndp {
        
        public FileReceiverEndpClient() {
        }
        
        public FileReceiverEndpClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileReceiverEndpClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileReceiverEndpClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileReceiverEndpClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFMiddleware.JEEWebservice.messageReaderResponse WCFMiddleware.JEEWebservice.FileReceiverEndp.messageReader(WCFMiddleware.JEEWebservice.messageReaderRequest request) {
            return base.Channel.messageReader(request);
        }
        
        public string messageReader(byte[] message, string key, string fileName) {
            WCFMiddleware.JEEWebservice.messageReaderRequest inValue = new WCFMiddleware.JEEWebservice.messageReaderRequest();
            inValue.Body = new WCFMiddleware.JEEWebservice.messageReaderRequestBody();
            inValue.Body.message = message;
            inValue.Body.key = key;
            inValue.Body.fileName = fileName;
            WCFMiddleware.JEEWebservice.messageReaderResponse retVal = ((WCFMiddleware.JEEWebservice.FileReceiverEndp)(this)).messageReader(inValue);
            return retVal.Body.messageReceived;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFMiddleware.JEEWebservice.messageReaderResponse> WCFMiddleware.JEEWebservice.FileReceiverEndp.messageReaderAsync(WCFMiddleware.JEEWebservice.messageReaderRequest request) {
            return base.Channel.messageReaderAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFMiddleware.JEEWebservice.messageReaderResponse> messageReaderAsync(byte[] message, string key, string fileName) {
            WCFMiddleware.JEEWebservice.messageReaderRequest inValue = new WCFMiddleware.JEEWebservice.messageReaderRequest();
            inValue.Body = new WCFMiddleware.JEEWebservice.messageReaderRequestBody();
            inValue.Body.message = message;
            inValue.Body.key = key;
            inValue.Body.fileName = fileName;
            return ((WCFMiddleware.JEEWebservice.FileReceiverEndp)(this)).messageReaderAsync(inValue);
        }
    }
}
